"""server.properties generator for PaperMC.

Reads the ``world`` section from a Config object and generates
a standard Minecraft server.properties file.
"""

from __future__ import annotations

import secrets
import string
from pathlib import Path

from config.loader import Config


def _random_password(length: int = 16) -> str:
    """Generate a random alphanumeric password for RCON."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


class ServerPropertiesGenerator:
    """Generates server.properties from the Config world section.

    Always enables RCON with a generated or user-supplied password
    so the management panel can function after first launch.
    """

    def __init__(self, config: Config) -> None:
        """Initialize with a Config object.

        Args:
            config: Fully populated Config dataclass.
        """
        self.config = config

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        rcon_password: str = "",
        rcon_port: int = 25575,
        server_port: int = 25565,
    ) -> str:
        """Generate server.properties content as a string.

        Args:
            rcon_password: RCON password (auto-generated if empty).
            rcon_port: RCON listening port.
            server_port: Minecraft game port.

        Returns:
            Complete server.properties content.
        """
        w = self.config.world
        password = rcon_password or _random_password()

        # Build lines in the order Minecraft writes them for readability
        lines = [
            "# Minecraft server properties",
            f"# Generated by MC Tunnel Controller",
            "",
            f"enable-rcon=true",
            f"rcon.port={rcon_port}",
            f"rcon.password={password}",
            "",
            f"server-port={server_port}",
            f"max-players={w.max_players}",
            f"motd={w.motd}",
            f"gamemode={w.gamemode}",
            f"difficulty={w.difficulty}",
            f"pvp={'true' if w.pvp else 'false'}",
            f"hardcore={'true' if w.hardcore else 'false'}",
            f"white-list={'true' if w.whitelist_enabled else 'false'}",
            # enforce-whitelist intentionally omitted — OPs should bypass whitelist (vanilla behaviour)
            f"online-mode={'true' if w.online_mode else 'false'}",
            f"allow-flight={'true' if w.allow_flight else 'false'}",
            f"allow-nether={'true' if w.allow_nether else 'false'}",
            f"allow-end={'true' if w.allow_end else 'false'}",
            f"enable-command-block={'true' if w.enable_command_block else 'false'}",
            f"spawn-protection={w.spawn_protection}",
            f"view-distance={w.view_distance}",
            f"simulation-distance={w.simulation_distance}",
            f"server-ip=",
            f"max-world-size=29999984",
            f"level-seed={w.seed}" if w.seed else "#level-seed=",
            f"level-name={w.level_name}",
        ]

        return "\n".join(lines) + "\n"

    def write(
        self,
        path: Path | str = "server/server.properties",
        rcon_password: str = "",
        rcon_port: int = 25575,
        server_port: int = 25565,
    ) -> str:
        """Write server.properties to disk.

        Args:
            path: Output file path.
            rcon_password: RCON password (auto-generated if empty).
            rcon_port: RCON listening port.
            server_port: Minecraft game port.

        Returns:
            The RCON password that was actually written (useful for the
            caller to configure the RCON client).
        """
        password = rcon_password or _random_password()
        content = self.generate(
            rcon_password=password,
            rcon_port=rcon_port,
            server_port=server_port,
        )
        output = Path(path)
        output.write_text(content, encoding="utf-8")
        return password
